---
version: 1
name: Alfajores Testnet Build
trigger:
  branch:
    - develop
    - feature/*
  pull_request:
    enabled: false
archive:
  scheme: MobileStack-alfajores
  platform: iOS
  configuration: Release
  destination: generic/platform=iOS
test:
  enabled: false
environment:
  xcode: 16.0.0
  vars:
    - name: DEVELOPMENT_TEAM
      value: QZUQHFSF4H
    - name: CODE_SIGN_STYLE
      value: Automatic
steps:
  - name: Install Dependencies
    script: |
      cd ios
      pod install
  - name: Strip Bitcode
    script: |
      cd ios
      ./fix_bitcode_ios.sh
